# Generated by Django 5.1.7 on 2025-03-09 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cedis', '0003_rename_nombre_cedi_name'),
        ('shipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='cedi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cedis.cedi'),
        ),
    ]
