# Generated by Django 5.1.7 on 2025-03-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0002_ship_cedi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='Delivery_distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ship',
            name='Delivery_time',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
