# Generated by Django 5.1.7 on 2025-03-09 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0003_alter_ship_delivery_distance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ship',
            old_name='Delivery_distance',
            new_name='delivery_distance',
        ),
        migrations.RenameField(
            model_name='ship',
            old_name='Delivery_time',
            new_name='delivery_time',
        ),
    ]
