# Generated by Django 5.1.7 on 2025-03-08 19:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cellphone',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9_]+$', 'Solo letras, números y guiones bajos permitidos')]),
        ),
    ]
