# Generated by Django 5.1.7 on 2025-03-08 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cedis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cedi',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='cedi',
            old_name='longitude',
            new_name='long',
        ),
    ]
