# Generated by Django 5.1.7 on 2025-03-08 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cedis', '0002_rename_latitude_cedi_lat_rename_longitude_cedi_long'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cedi',
            old_name='nombre',
            new_name='name',
        ),
    ]
